- name: Download RHEL image
  get_url:
     url: http://www.opentlc.com/download/osp_advanced_networking/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
     dest: /tmp/rhel.qcow2
  tags:
      - tested
- name: Create openstack image
  os_image:
     cloud: "{{ cloud_name }}"
     name: "{{ item.value.name}}"
     container_format: "{{ item.value.container_format }}"
     disk_format: "{{ item.value.disk_format }}"
     state: "{{ state }}"
     filename: "{{ item.value.filename }}"
  with_dict: "{{ osp_image }}"
  tags:
      - tested
