- name: Generate key files
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/test_id_rsa

- name: Create OSP keypair
  os_keypair:
    cloud: "{{ cloud_name }}"
    state: "{{ state }}"
    name: "{{ item.value.name }}"
    public_key_file: "{{ item.value.public_key }}"
  with_dict: "{{ osp_keypair }}"
